# ---------- 1) 빌드 스테이지 ----------
FROM node:22 AS builder

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml nest-cli.json tsconfig.json ./
COPY libs ./libs
COPY apps ./apps

# 빌드 스테이지 (Debian 기반)에서 npm 전역설치
RUN npm install -g pnpm

# 의존성 설치 & API 빌드
RUN pnpm install
RUN pnpm build:api

# ---------- 2) 런타임 스테이지 ----------
FROM node:22-alpine
WORKDIR /app

# 1) bash + curl + timezone 설치
RUN apk add --no-cache bash curl tzdata && \
    ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
    echo "Asia/Seoul" > /etc/timezone

# 빌드 산출물 & package.json 등 복사
COPY --from=builder /app/dist ./dist
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN npm install -g pnpm
RUN pnpm install --prod

EXPOSE 3000

CMD ["node", "dist/apps/api/src/main"]
