version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: api-service
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  cron:
    build:
      context: .
      dockerfile: apps/cron/Dockerfile
    container_name: cron-service
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: .
      dockerfile: apps/next-frontend/Dockerfile
    container_name: frontend-service
    ports:
      - "3001:3001"
    environment:
      API_URL: http://api-service:3000
      NODE_ENV: production
