version: '3.8'

services:
  api:
    image: ghcr.io/jeongkichang/check-the-deposit-history/api:latest
    container_name: api-service
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      env_file: .env

  cron:
    image: ghcr.io/jeongkichang/check-the-deposit-history/cron:latest
    container_name: cron-service
    environment:
      NODE_ENV: production
      env_file: .env

  frontend:
    image: ghcr.io/jeongkichang/check-the-deposit-history/frontend:latest
    container_name: frontend-service
    ports:
      - "3001:3001"
    environment:
      API_URL: http://api-service:3000
      NODE_ENV: production
